### ISSUE TITLE
The URI to the manifest is served via github.io … but IIIF requires CORS headers, which are not available via the github web projection.

### ISSUE THREAD

**Issue by jainn3** [american-art/iiif#1]
• The URI to the manifest is served via github.io … but IIIF requires CORS headers, which are not available via the github web projection.

Looks like github pages does support CORS headers.

Sources:
http://stackoverflow.com/questions/26416727/cross-origin-resource-sharing-on-github-pages
https://twitter.com/invisiblecomma/status/575219895308324864

**Comment by workergnome** [comment]
🎈 Fantastic. 🎈

 That's been changed from the last time we tried to do this.
